#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: r1
#          #            uri: http://localhost:8081
#          uri: lb://CUSTOMER-SERVICE
#          predicates:
#            - Path= /api/customers/**
#        - id: r2
#          uri: lb://INVENTORY-SERVICE
#          predicates:
#            - Path= /api/products/**
